### PR TITLE
Fix hatch-is/loopback-testing

### PR DESCRIPTION
**Pull request by kostia-official**
@jrschumacher In https://github.com/hatch-is/loopback-testing/commit/245e0a2d3912a28ee488c34594a997cf666a835d you renamed `beforeEach` to `before`. We should to do that in this file too.

### CODE REVIEW

**Comment by kostia-official** [comment]
@jrschumacher After loopback update `givenLoggedInUser` creates new user instance. But for ACL testing we need to login already created user. Please merge this PR. In future we can find more elegance way to solve this.

**Comment by jrschumacher** [comment]
@kozzztya nice!

**Comment by jrschumacher** [comment]
Also in the future will you add a test for these helpers.

**Comment by kostia-official** [comment]
@jrschumacher yes, I was should start from test)

**Pull request merged**
